name: 'Get & Cache Node Dependencies'
description: 'Get and cache dependencies for a Node.js project'
inputs:
  use-yarn:
    description: 'Whether to use Yarn (v1) instead of npm'
    required: false
    default: 'false'
  # Path to the node_modules directory
  node-modules-path:
    description: 'Path to the node_modules directory'
    required: false
    default: './node_modules'
runs:
  using: 'composite'
  steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies NPM
        if: ${{ inputs.use-yarn }} == 'false'
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ inputs.node-modules-path }}
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' && ${{ inputs.use-yarn }} == 'false'
        run: npm ci
        shell: bash
      - name: Cache dependencies Yarn
        if: ${{ inputs.use-yarn }} == 'true'
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: ${{ inputs.node-modules-path }}
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies Yarn
        if: steps.cache-yarn.outputs.cache-hit != 'true' && ${{ inputs.use-yarn }} == 'true'
        run: yarn install --frozen-lockfile
        shell: bash
